port: "8080"
mongo_url: "mongodb://localhost:27017/db_name"
# mongo_url: "mongodb://username:password@host:27017/db_name"
database_name: "db_name"
log_level: "info"
jwt_secret: "your-super-secret-jwt-key-change-this-in-production"

# Redis Cache Env
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
